/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' },],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  "wms": [
    //id of the sidebar
    {
      type: "category", // doc(default), 'link'(external links), 'ref'(page without without sidebar)
      label: "WMS",
      collapsed: false,
      items: [
        "wms/intro", //folder_name/file_name
        // "wms/zowe-architecture",
        // "wms/zowe-secure-setup",
      ],
    },
   
    
  
    // {
    //   type: "category",
    //   label: "Migrating from V1 to V2",
    //   items: [
    //     "extend/migrate-extensions",
    //   ],
    // },
    // "getting-started/zowe-resources",
  ],
};

module.exports = sidebars;
